#!/bin/bash
rev=$1
[ -z "$rev" ] && rev="HEAD"

tests=`git diff-tree --no-commit-id --name-only --diff-filter="[A|C|M|R]" -r $rev | grep -E "*\.html" | sed -E 's@.*/(.*)\.html@\1@g'`
if [[ $tests == "" ]] ;then exit 0; fi
echo $tests | tr " " "\n"

read -p "Those tests will be installed. Are you sure? [y] " -n 1
echo ""
if [[ ! $REPLY =~ ^[y]$ ]]
then
    exit 1
fi
SIGN=1 ~/ctc/installCTC.sh run --id $tests
