#!/bin/bash

REV="$1"
if [ -z "$REV" ]; then
  echo "Provide branch name/revision"
  exit 1
fi

FORK_POINT=$(git merge-base --fork-point $REV)
FIRST_COMMIT=$(git child $FORK_POINT)
COMMIT_MESSAGE=$(git log -n 1 --pretty=format:'%s' $FIRST_COMMIT)
git reset --hard "$REV" && git merge --squash HEAD@{1} && git commit -m "$COMMIT_MESSAGE"
