#!/bin/bash

# http://stackoverflow.com/questions/750172/change-the-author-of-a-commit-in-git/870367#870367
EMAIL_FROM=${1}
EMAIL_TO=${2}
# You cannot apply the filter-branch in the middle of the history
# http://stackoverflow.com/questions/15250070/running-filter-branch-over-a-range-of-commits
SHA_FROM=${3}
RANGE="HEAD"

function usage() {
    echo "Usage:"
    echo "  git change-email EMAIL_FROM EMAIL_TO"
}

if [ -z "$EMAIL_FROM" -o -z "$EMAIL_TO" ]; then
    usage
    exit 1
fi

if [ ! -z "$SHA_FROM" ]; then
    RANGE="${SHA_FROM}..HEAD"
fi

git filter-branch -f --env-filter "if [ \"\$GIT_AUTHOR_EMAIL\" = $EMAIL_FROM ]; then GIT_AUTHOR_EMAIL=$EMAIL_TO; GIT_COMMITTER_EMAIL=$EMAIL_TO; fi" $RANGE

