#!/bin/bash

# http://stackoverflow.com/questions/750172/change-the-author-of-a-commit-in-git/870367#870367
EMAIL_FROM=${1}
EMAIL_TO=${2}
SHA_FROM=${3}

# TODO: add condition if sha_from not provided
git filter-branch -f --env-filter "if [ \"\$GIT_AUTHOR_EMAIL\" = $EMAIL_FROM ]; then GIT_AUTHOR_EMAIL=$EMAIL_TO; GIT_COMMITTER_EMAIL=$EMAIL_TO; fi" "${SHA_FROM}..HEAD"
