#!/bin/sh
#http://stackoverflow.com/a/6719718/588759
#http://stackoverflow.com/a/4522043/588759
#http://unix.stackexchange.com/a/41751/37431
#http://stackoverflow.com/a/4448922/588759
#http://stackoverflow.com/questions/957928/is-there-a-way-to-get-the-git-root-directory-in-one-command/957978#957978
cd "$(git rev-parse --show-toplevel)" && git diff-tree --no-commit-id --name-only -r $1 | xargs ~/ctc/verification/validate-js.py | sed '/^$/N;/^\n$/D' | sed '1{/^$/d}' | sed '${/^$/d;}'
