#!/bin/bash
# http://stackoverflow.com/questions/454734/how-can-one-change-the-timestamp-of-an-old-commit-in-git/24584976#24584976

function usage() {
echo Usage:
echo "  script \"YYYY-mm-dd HH:MM\" <sha>"
echo
}

date="$1"
commit="$2"

if [ -z "${date}" ]; then
    usage
    exit 1
fi

if [ -z "${commit}" ]; then
    usage
    exit 1
fi

datecal="$date":`date +"%S"`
temp_branch="temp-rebasing-branch"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

date_timestamp=$(date -d "$datecal" +%s)
date_r=$(date -R -d "$datecal")
echo $date_r

if [[ -z "$commit" ]]; then
    exit 0
fi

git checkout -b "$temp_branch" "$commit"
GIT_COMMITTER_DATE="$date_timestamp" GIT_AUTHOR_DATE="$date_timestamp" git commit --amend --no-edit --date "$date_r"
git checkout "$current_branch"
git rebase  --autostash --committer-date-is-author-date "$commit" --onto "$temp_branch"
git branch -d "$temp_branch"
