#!/bin/bash

# http://stackoverflow.com/questions/750172/change-the-author-of-a-commit-in-git/870367#870367
echo email_from=${1}
echo email_to=${2}
echo sha_from=${3}
read -d '' cmd << EOF
if [ \"\$GIT_AUTHOR_EMAIL\" = "rofrol@gmail.com" ]; then
	GIT_COMMITTER_EMAIL="${2}";
	GIT_AUTHOR_EMAIL="${2}";
	git commit-tree \"\$@\";
else
	git commit-tree \"\$@\";
fi
EOF

echo "$cmd"

# TODO: add condition if sha_from not provided
git filter-branch --commit-filter "${cmd}" ${3}..HEAD
